### ISSUE TITLE
`clingraph 0.1.0.post7` crashes when installed via pip

### ISSUE THREAD

**Issue by teiesti** [potassco/clingraph#59]
When I install the current beta version via pip, it crashes even with the simplest commands.

```
$ sudo pip install --extra-index-url https://test.pypi.org/simple/ clingraph
Looking in indexes: https://pypi.org/simple, https://test.pypi.org/simple/
Collecting clingraph
  Downloading https://test-files.pythonhosted.org/packages/c5/c1/a07e6898415814cb1cccbf700ab078141bc6a92dc896e37e4ab0d3a5fcca/clingraph-0.1.0.post7-py3-none-any.whl (13 kB)
Requirement already satisfied: networkx>=2.6 in /usr/lib/python3.10/site-packages (from clingraph) (2.7)
Requirement already satisfied: jsonschema>=4.0 in /usr/lib/python3.10/site-packages (from clingraph) (4.4.0)
Requirement already satisfied: clingo>=5.5 in /usr/lib/python3.10/site-packages (from clingraph) (5.5.1)
Requirement already satisfied: clorm>=1.3.6 in /usr/lib/python3.10/site-packages (from clingraph) (1.3.6)
Requirement already satisfied: graphviz>=0.19.0 in /usr/lib/python3.10/site-packages (from clingraph) (0.19)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/lib/python3.10/site-packages (from jsonschema>=4.0->clingraph) (0.18.1)
Requirement already satisfied: attrs>=17.4.0 in /usr/lib/python3.10/site-packages (from jsonschema>=4.0->clingraph) (21.4.0)
Installing collected packages: clingraph
Successfully installed clingraph-0.1.0.post7
$ clingraph --version
Traceback (most recent call last):
  File "/usr/bin/clingraph", line 5, in <module>
    from clingraph import main
  File "/usr/lib/python3.10/site-packages/clingraph/__init__.py", line 11, in <module>
    from .graphviz import compute_graphs, dot, render
ModuleNotFoundError: No module named 'clingraph.graphviz'
```

With `clingraph 0.1.0.post6` these commands work fine.

**Comment by susuhahnml** [comment]
Have you tried this in a clean environment. Looks like it is searching in an old installation of clingraph.

**Comment by florianfischer91** [comment]
I get the same exception.
Additionally when i use `pip install -i https://test.pypi.org/simple/ clingraph==0.1.0.post7` as described here https://test.pypi.org/project/clingraph/0.1.0.post7/#description the installation fails because jsonschema>=4.0 could not be found at test.pypi

**Comment by teiesti** [comment]
> Have you tried this in a clean environment? Looks like it is searching in an old installation of clingraph.

Yes, I have uninstalled the old version of clingraph before with `pip uninstall clingraph` and I have also verified that nothing was left on my system.

**Comment by florianfischer91** [comment]
It seems that the graphviz-dir is missing in the wheel?

**Comment by susuhahnml** [comment]
Can you try the new version? This should now be fixed. @florianfischer91 @teiesti

**Comment by teiesti** [comment]
Looks good.
